name: tradukejo

networks:
  django_network:

services:

  django:
    build:
      context: .
      target: development
    restart: always
    depends_on:
      mariadb:
        condition: service_healthy
      # vue-build:
      #   condition: service_completed_successfully
    volumes:
      - .:/app:z
      - ./.venv:/app/.venv:z
    working_dir: /app
    environment:
      DJANGO_SETTINGS_MODULE: tradukejo.settings
      MARIADB_HOST: mariadb
      MARIADB_NAME: $MARIADB_DATABASE
      MARIADB_USER: $MARIADB_USER
      MARIADB_PASSWORD: $MARIADB_PASSWORD
    user: ${USER_ID-1000}:${GROUP_ID-1000}
    command: >
      sh -c "
      python manage.py migrate &&
      python manage.py loaddata languages.json &&
      python manage.py collectstatic --noinput &&
      python manage.py compilemessages -v0 &&
      python manage.py runserver 0.0.0.0:${DJANGO_PORT}
      "
    # granian --interface wsgi --blocking-threads 3 config.wsgi:application --host 0.0.0.0 --port 8000
    networks:
      - django_network
    ports:
      - $DJANGO_PORT:$DJANGO_PORT

  vue-build:
    image: node:16.20-slim
    working_dir: /app/vue-translation-interface
    user: ${USER_ID-1000}:${USER_ID-1000}
    volumes:
      - .:/app:z
    command: /bin/sh -c "npm i; npm run --verbose build"

  vue-build-watch:
    extends: vue-build
    profiles: ["exclude"]
    tty: true
    command: "npm install && npm run build-watch"

  mariadb:
    image: mariadb:10.11.11
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: $MARIADB_ROOT_PASSWORD
      MARIADB_DATABASE: $MARIADB_DATABASE
      MARIADB_USER: $MARIADB_USER
      MARIADB_PASSWORD: $MARIADB_PASSWORD
    volumes:
      - .docker/mariadb_data:/var/lib/mysql:z
    networks:
      - django_network
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      start_period: 3s
      interval: 30s
      timeout: 2s
      retries: 3
